language: python

branches:
  only:
    - /.*/
matrix:
  include:
    - python: 3.6
      env: TOXENV=py36

    - python: 3.5
      env: TOXENV=py35

    - python: 3.7
      dist: xenial
      sudo: true
      env: TOXENV=py37

    - python: 3.5
      env: TOXENV=lint

install:
  - pip install tox coveralls

script:
  - tox

after_success:
  - coveralls
